export default trackJson = [
  {
    "yqtblgx": "",
    "zwhsjqj": "",
    "rbyy": "在武汉停留多日",
    "bzzzytjd": "病例1：患者男性，33岁，在武汉工作，1月11日出现发热、畏寒，1月17日返回大连，当日因发热、咳嗽等症状入院隔离治疗。1月22日，经国家卫生健康委疫情领导小组下设诊断专家组确认为新型冠状病毒感染的肺炎确诊病例。目前，患者属重症病例，生命体征平稳，其密切接触者56人均在医学观察中。",
    "bk": "重症",
    "xb": "男",
    "rysj": "2020/1/17",
    "lssj": "2020/1/17",
    "fbingsj": "2020/1/11",
    "fbrq": "1月22日",
    "jzd": "武汉",
    "fbusj": "1月22日",
    "nl": "33",
    "blh": "1",
    "nationality&native":["",""],
    "treatment_hospital":"",
    "reason": '湖北居住',
    "detailReason": '密切接触',
    "origin": '湖北',
    "track": [],
  },
  {
    "yqtblgx": "病例12儿子",
    "zwhsjqj": "",
    "rbyy": "在武汉停留多日",
    "bzzzytjd": "病例2：患者男性，37岁，在武汉工作，1月16日患者出现全身不适、畏寒症状，1月20日返连，23日上午入院就诊。目前患者病情稳定。在连密切接触者12人，居家医学观察中。",
    "bk": "稳定",
    "xb": "男",
    "rysj": "2020/1/23",
    "lssj": "2020/1/20",
    "fbingsj": "2020/1/16",
    "fbrq": "1月23日",
    "jzd": "武汉",
    "fbusj": "1月26日",
    "nl": "37",
    "blh": "2",
    "nationality&native":["",""],
    "treatment_hospital":"",
    "reason": '湖北居住',
    "detailReason": '密切接触',
    "origin": '武汉',
    "track": [],
  },
  {
    "yqtblgx": "病例5儿子",
    "zwhsjqj": "",
    "rbyy": "在湖北停留",
    "bzzzytjd": "病例3：患者男性，46岁，1月9日从湖南至武汉天河机场返连，1月11日在大连家中发热，24日入院就诊。患者诊断是重症病例，目前病情尚平稳，积极治疗中。在连密切接触者15人，居家医学观察中。",
    "bk": "稳定",
    "xb": "男",
    "rysj": "2020/1/24",
    "lssj": "2020/1/9",
    "fbingsj": "2020/1/11",
    "fbrq": "1月24日",
    "jzd": "大连",
    "fbusj": "1月26日",
    "nl": "46",
    "blh": "3",
    "nationality&native":["",""],
    "treatment_hospital":"",
    "reason": '湖北停留',
    "detailReason": '密切接触',
    "origin": '武汉',
    "track": [{
      "from": "武汉",
      "to": "大连",
      "time": "2020/1/9",
      "tran":"plane"
    }],
  },
]